import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "./AuthSessionProvider"; // ★ 1. 임포트

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja"> {/* lang="ja"로 변경 */}
      <body className={inter.className}>
        {/* ★ 2. <AuthSessionProvider>로 children을 감쌉니다 */}
        <AuthSessionProvider>{children}</AuthSessionProvider>
      </body>
    </html>
  );
}